// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.2
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Id, StatusResponse, User } from "./user";

export const protobufPackage = "auth.v1";

/** Message for sign up request */
export interface SignUpRequest {
  name?: string | null | undefined;
  email: string;
  password: string;
  phoneNumber?: string | null | undefined;
}

/** Message for sign in request */
export interface SignInRequest {
  email: string;
  password: string;
  clientInfo?: ClientInfo | null | undefined;
}

/** Message for client information (used in sign in) */
export interface ClientInfo {
  ipAddress?: string | null | undefined;
  userAgent?: string | null | undefined;
}

/** Message for verify email request */
export interface VerifyEmailRequest {
  token: string;
  clientInfo?: ClientInfo | null | undefined;
}

/** Message for sigh in / verify email response containing tokens */
export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  user: User | null;
}

/** Message for refresh tokens response */
export interface RefreshTokensResponse {
  accessToken: string;
  refreshToken: string;
}

/** Message representing a token */
export interface Token {
  token: string;
}

/** Message representing an email */
export interface Email {
  email: string;
}

/** Message for setting a new password */
export interface SetNewPasswordRequest {
  token: string;
  password: string;
}

/** Message for signing out from other devices */
export interface SignOutRequest {
  userId: string;
  currentSessionId: string;
}

export const AUTH_V1_PACKAGE_NAME = "auth.v1";

/** AuthService defines the gRPC service for authentication. */

export interface AuthServiceClient {
  /** rpc to sign up a user */

  signUp(request: SignUpRequest): Observable<User>;

  /** rpc to sign in a user */

  signIn(request: SignInRequest): Observable<AuthResponse>;

  /** rpc to verify email */

  verifyEmail(request: VerifyEmailRequest): Observable<AuthResponse>;

  /** rpc to resend confirmation email */

  resendConfirmationEmail(request: Email): Observable<StatusResponse>;

  /** rpc to refresh tokens */

  refreshTokens(request: Token): Observable<RefreshTokensResponse>;

  /** rpc to reset password */

  initResetPassword(request: Email): Observable<StatusResponse>;

  /** rpc to resend reset password email */

  resendResetPasswordEmail(request: Email): Observable<StatusResponse>;

  /** rpc to set new password */

  setNewPassword(request: SetNewPasswordRequest): Observable<StatusResponse>;

  /** rpc to sign out a user from current device */

  signOutCurrentDevice(request: SignOutRequest): Observable<StatusResponse>;

  /** rpc to sign out a user from other devices */

  signOutOtherDevices(request: SignOutRequest): Observable<StatusResponse>;

  /** rpc to sign out a user from all devices */

  signOutAllDevices(request: Id): Observable<StatusResponse>;
}

/** AuthService defines the gRPC service for authentication. */

export interface AuthServiceController {
  /** rpc to sign up a user */

  signUp(request: SignUpRequest): Promise<User> | Observable<User> | User;

  /** rpc to sign in a user */

  signIn(request: SignInRequest): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  /** rpc to verify email */

  verifyEmail(request: VerifyEmailRequest): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  /** rpc to resend confirmation email */

  resendConfirmationEmail(request: Email): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to refresh tokens */

  refreshTokens(
    request: Token,
  ): Promise<RefreshTokensResponse> | Observable<RefreshTokensResponse> | RefreshTokensResponse;

  /** rpc to reset password */

  initResetPassword(request: Email): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to resend reset password email */

  resendResetPasswordEmail(request: Email): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to set new password */

  setNewPassword(request: SetNewPasswordRequest): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to sign out a user from current device */

  signOutCurrentDevice(request: SignOutRequest): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to sign out a user from other devices */

  signOutOtherDevices(request: SignOutRequest): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to sign out a user from all devices */

  signOutAllDevices(request: Id): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "signUp",
      "signIn",
      "verifyEmail",
      "resendConfirmationEmail",
      "refreshTokens",
      "initResetPassword",
      "resendResetPasswordEmail",
      "setNewPassword",
      "signOutCurrentDevice",
      "signOutOtherDevices",
      "signOutAllDevices",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
