// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.2
// source: menu-category.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";
import { FlatMenuItemWithTranslation, MenuItemWithTranslation } from "./menu-item";

export const protobufPackage = "menu_category.v1";

/** declaration of Language message */
export interface Language {
  language: string;
}

/** declaration of Id message */
export interface Id {
  id: string;
}

/** Message representing a list of menu categories with translations */
export interface MenuCategoryListWithTranslation {
  data: MenuCategoryWithTranslation[];
}

/** Message representing a menu category */
export interface MenuCategory {
  id: string;
  slug: string;
  position: number;
  imageUrl?: string | null | undefined;
  isAvailable: boolean;
  createdAt: Date | null;
  updatedAt: Date | null;
}

/** Message representing full menu response with categories and items */
export interface FullMenuResponse {
  categories: FlatMenuCategoryWithItems[];
}

/** Message representing a menu category translation */
export interface MenuCategoryTranslation {
  id: string;
  language: string;
  title: string;
  description?: string | null | undefined;
}

/** Message representing a menu category with translation */
export interface MenuCategoryWithTranslation {
  id: string;
  slug: string;
  position: number;
  imageUrl?: string | null | undefined;
  isAvailable: boolean;
  translations: MenuCategoryTranslation[];
}

/** Message representing a menu category with items */
export interface MenuCategoryWithItems {
  id: string;
  slug: string;
  position: number;
  imageUrl?: string | null | undefined;
  isAvailable: boolean;
  translations: MenuCategoryTranslation[];
  menuItems: MenuItemWithTranslation[];
}

/** Message representing a flat menu category with items for a specific language */
export interface FlatMenuCategoryWithItems {
  id: string;
  slug: string;
  position: number;
  isAvailable: boolean;
  language: string;
  title: string;
  description?: string | null | undefined;
  imageUrl?: string | null | undefined;
  menuItems: FlatMenuItemWithTranslation[];
}

/** Request message for creating a menu category. */
export interface CreateMenuCategoryRequest {
  slug: string;
  imageUrl?: string | null | undefined;
  isAvailable?: boolean | null | undefined;
}

/** Request message for updating a menu category. */
export interface UpdateMenuCategoryRequest {
  id: string;
  slug?: string | null | undefined;
  imageUrl?: string | null | undefined;
  isAvailable?: boolean | null | undefined;
}

/** Request message for changing the position of a menu category. */
export interface ChangeMenuCategoryPositionRequest {
  id: string;
  position: number;
}

/** Request message for creating a menu category translation. */
export interface CreateMenuCategoryTranslationRequest {
  categoryId: string;
  language: string;
  title: string;
  description?: string | null | undefined;
}

/** Request message for updating a menu category translation. */
export interface UpdateMenuCategoryTranslationRequest {
  id: string;
  title?: string | null | undefined;
  description?: string | null | undefined;
}

/** Message representing a status response */
export interface StatusResponse {
  success: boolean;
  message: string;
}

export const MENU_CATEGORY_V1_PACKAGE_NAME = "menu_category.v1";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

/** MenuCategoryService defines the gRPC service for managing menu categories. */

export interface MenuCategoryServiceClient {
  /** rpc to get full menu by language */

  getFullMenuByLanguage(request: Language): Observable<FullMenuResponse>;

  /** rpc to get menu categories by language */

  getMenuCategoriesByLanguage(request: Language): Observable<MenuCategoryListWithTranslation>;

  /** rpc to get a menu category by its ID */

  getMenuCategoryById(request: Id): Observable<MenuCategoryWithTranslation>;

  /** rpc to create a new menu category */

  createMenuCategory(request: CreateMenuCategoryRequest): Observable<MenuCategory>;

  /** rpc to update an existing menu category */

  updateMenuCategory(request: UpdateMenuCategoryRequest): Observable<MenuCategory>;

  /** rpc to change the position of a menu category */

  changeMenuCategoryPosition(request: ChangeMenuCategoryPositionRequest): Observable<MenuCategory>;

  /** rpc to delete a menu category by its ID */

  deleteMenuCategory(request: Id): Observable<StatusResponse>;

  /** rpc to create a new category translation */

  createMenuCategoryTranslation(request: CreateMenuCategoryTranslationRequest): Observable<MenuCategoryTranslation>;

  /** rpc to update an existing category translation */

  updateMenuCategoryTranslation(request: UpdateMenuCategoryTranslationRequest): Observable<MenuCategoryTranslation>;

  /** rpc to delete a category translation by its ID */

  deleteMenuCategoryTranslation(request: Id): Observable<StatusResponse>;
}

/** MenuCategoryService defines the gRPC service for managing menu categories. */

export interface MenuCategoryServiceController {
  /** rpc to get full menu by language */

  getFullMenuByLanguage(request: Language): Promise<FullMenuResponse> | Observable<FullMenuResponse> | FullMenuResponse;

  /** rpc to get menu categories by language */

  getMenuCategoriesByLanguage(
    request: Language,
  ):
    | Promise<MenuCategoryListWithTranslation>
    | Observable<MenuCategoryListWithTranslation>
    | MenuCategoryListWithTranslation;

  /** rpc to get a menu category by its ID */

  getMenuCategoryById(
    request: Id,
  ): Promise<MenuCategoryWithTranslation> | Observable<MenuCategoryWithTranslation> | MenuCategoryWithTranslation;

  /** rpc to create a new menu category */

  createMenuCategory(
    request: CreateMenuCategoryRequest,
  ): Promise<MenuCategory> | Observable<MenuCategory> | MenuCategory;

  /** rpc to update an existing menu category */

  updateMenuCategory(
    request: UpdateMenuCategoryRequest,
  ): Promise<MenuCategory> | Observable<MenuCategory> | MenuCategory;

  /** rpc to change the position of a menu category */

  changeMenuCategoryPosition(
    request: ChangeMenuCategoryPositionRequest,
  ): Promise<MenuCategory> | Observable<MenuCategory> | MenuCategory;

  /** rpc to delete a menu category by its ID */

  deleteMenuCategory(request: Id): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to create a new category translation */

  createMenuCategoryTranslation(
    request: CreateMenuCategoryTranslationRequest,
  ): Promise<MenuCategoryTranslation> | Observable<MenuCategoryTranslation> | MenuCategoryTranslation;

  /** rpc to update an existing category translation */

  updateMenuCategoryTranslation(
    request: UpdateMenuCategoryTranslationRequest,
  ): Promise<MenuCategoryTranslation> | Observable<MenuCategoryTranslation> | MenuCategoryTranslation;

  /** rpc to delete a category translation by its ID */

  deleteMenuCategoryTranslation(request: Id): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function MenuCategoryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getFullMenuByLanguage",
      "getMenuCategoriesByLanguage",
      "getMenuCategoryById",
      "createMenuCategory",
      "updateMenuCategory",
      "changeMenuCategoryPosition",
      "deleteMenuCategory",
      "createMenuCategoryTranslation",
      "updateMenuCategoryTranslation",
      "deleteMenuCategoryTranslation",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MenuCategoryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MenuCategoryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MENU_CATEGORY_SERVICE_NAME = "MenuCategoryService";
